inherit_gem:
  google-style: google-style.yml

AllCops:
  Exclude:
    - "acceptance/**/*"
    - "google-cloud-translate.gemspec"
    - "Rakefile"
    - "support/**/*"
    - "test/**/*"
Documentation:
  Enabled: false
Metrics/MethodLength:
  Exclude:
    - "lib/google/cloud/translate.rb"
Naming/FileName:
  Exclude:
    - "lib/google-cloud-translate.rb"
